### ISSUE TITLE
how to get temperature data

### ISSUE THREAD

**Issue by MujoNoThuki** [LaboratoireMecaniqueLille/Seek-thermal-Python#2]
Hi. Thanks to this program, I was able to take thermal images with SeekPro in python. Is it possible to get temperature information with this program?

**Comment by Dad0u** [comment]
Hi, for now this program is only meant to recover raw images from the sensor dans does not perform any kind of calibration. A calibration is necessary in order to retrieve a temperature. It should be noted that the measured flux on a pixel is not only a function of the temperature, but also depends on emissivity of the material being observed so there is no direct relationship between measurement and temperature. Emissivity is usually assumed and calibration is typically performed by measuring the flux for several known temperature on every pixel. I don't have the time to add a calibration function but i would be happy to review pull requests implementing it.

**Comment by MujoNoThuki** [comment]
i understood, thank you.
