### ISSUE TITLE
ice pack

### ISSUE THREAD

**Issue by MujoNoThuki** [LaboratoireMecaniqueLille/Seek-thermal-Python#3]
Long time no see.
When I took a picture of the ice pack, it looks like the image.
The part of the ice pack is white, but usually the part where the temperature is low should be black, so I wondered why. How can I solve it?

![image_41](https://user-images.githubusercontent.com/74951659/122722358-9622c100-d2ac-11eb-934b-b12be302f4b4.png)

**Comment by Dad0u** [comment]
Hello, this is very likely related to the issue #1 : the offset of 1600 applied to the calibration image (see line 164) was chosen arbitrarily and was not tested on a wide range of values. This can cause an overflow as the image is unsigned and the substracted calibration image is not guaranteed to be smaller in than the current frame on all pixels. This is expected to happen on extreme values (cold or hot). 
One simple workaround would be to cast the image in int32 instead of uint16 to allow negative values in the image, but this would mean that the image could contain negative values, which is unusual. A "cleaner" workaround would be to fully understand the ranges of the calibration image and the measured image and choose the types of the image and the value of the offset so that the resulting image is guaranteed to fall into the expected type without overflow, but i did not have the time to perform this study at the time.
I hope this will help you solve the issue. If you manage to do so, fell free to submit a pull request to contribute to this project.

**Comment by MujoNoThuki** [comment]
I'm sorry I'm not good at English.
I changed code.

return status,np.frombuffer(ret,dtype=np.uint16).reshape... → np.int16
in [def grab(self):]

![a](https://user-images.githubusercontent.com/74951659/123938430-11cded80-d9d2-11eb-9ea0-46650ab246d5.PNG)
